### ISSUE TITLE
Does not work!!!

### ISSUE THREAD

**Issue by hamed-bolhasani** [mitrm/yii2-image-cutter-size#1]
hi i install your extension with composer and this error happend!
**Class 'sadovojav\cutter\behaviors\CutterBehavior' not found**
i changed  **use sadovojav\cutter\behaviors\CutterBehavior** to **use mitrm\cutter\behaviors\CutterBehavior;** in model file and this error solved! 

but in view file This error is displayed to me : **Class 'sadovojav\cutter\Cutter' not found**
what should I do?!?!?!?!

**Comment by mitrm** [comment]
use it https://packagist.org/packages/sadovojav/yii2-image-cutter

**Comment by hamed-bolhasani** [comment]
What is the difference between the two?
These are the same!!!

**Comment by mitrm** [comment]
I corrected the instruction https://github.com/mitrm/yii2-image-cutter-size/blob/master/README.md
Check again please

**Comment by hamed-bolhasani** [comment]
tank you it work now!

how can i create my custom language and set it to default?
i create a folder in **messages folder** and translate **cutter.php** file to my language and in **registerTranslations** method i changed **sourceLanguage** to (for example fa-IR) But that did not work!

**Comment by mitrm** [comment]
should work as described here https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-i18n.md

**Comment by hamed-bolhasani** [comment]
I really thank you for the patience.

I'm trying to get my question upright!

Can not move the frame horizontally? To select a region of the photo.

**Comment by hamed-bolhasani** [comment]
i solved it by css command in **cropper.css** file!!!!

i add **direction: ltr;** to **.cropper-bg** section and it work fine!!

**Comment by mitrm** [comment]
I checked, corrected composer.json update the package please
